# -*- coding: utf-8 -*-
"""Python(day37).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pq7VDcbsZYTe8QLBcbhgryT8L0XIiuNg
"""

my_info = {'first name': 'Shristi','last name': 'Ghimire','age': 21,'city': 'Arlington'}
for key, value in my_info.items():
    print(value)
for key, value in my_info.items():
    print(f"My {key} is {value}.")

capital_cities = {'USA': 'DC','Nepal': 'Kathmandu','Japan': 'Tokyo'}
capital_cities['UK'] = 'London'
for country, capital in capital_cities.items():
    print(f"{capital} is the capital of {country}.")
print("The following countries are included:")
for country in capital_cities.keys():
    print(country)
print("The following cities are included:")
for capital in capital_cities.values():
    print(capital)

countries = {'Nepal': { 'city': 'Kathmandu', 'population': '1.4million', 'fact': 'Mount Everest is in Nepal'},
    'USA': {'city': 'DC','population': '30 million','fact': 'It is a free country'},
    'India': {'city': 'Delhi', 'population': '2 billion', 'fact': 'India exports lots of grains.'}}
for country, info in countries.items():
    print(f"The capital of {country} is {info['city']}. Its population is {info['population']}. An interesting fact about {country} is {info['fact']}.")

groceries = {'milk': 'gallon','bread': 'loaf','eggs': 'dozen','apples': 'bag','cereal': 'box'}
for item, quantity in groceries.items():
    print(f"{item}: {quantity}")
groceries = {'milk': ['gallon', 'aisle 1'],'bread': ['loaf', 'aisle 2'],'eggs': ['dozen', 'aisle 1'],'apples': ['bag', 'aisle 3'],'cereal': ['box', 'aisle 4']}
for item, details in groceries.items():
    print(f"In {details[1]}, pick up a {details[0]} of {item},Thanks.")