# -*- coding: utf-8 -*-
"""Python(day7).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124cxrvSpbIJa5dxGt4WUNaDX-QwSvIRu
"""

print("Dr. \n\tConrad")

print("Dr. \t\nConrad")

name="Shristi"
print(f"Hello\n\t{name}".upper())

name="shristi"
x="professor"
print("\t\n",name,x.title())   #.title() is the method that makes all the first letters of a word uppercase
#Note: each variable needs it's own method
print("\t\n",name.title(),x.title())  #here both variables havetheir own methods

"aplha"

"alpha"
"beta"   #when we don't give any instructions it just runs the last line

alpha=3                #3 is an integer, integer is a whole number
print(type(alpha))

alpha = "beta"  #is there is
print(type(alpha))

print(alpha) #even if we think alpha has bo value here, collab will remember the value of alpha from previous code unless we give a new value to the variables.

"""Operations{these are for numbers or integers}: add(+), substract(-),exponent(**)"""

3**3 #** is exponent

3*3 #* is multiply

gamma = 3**3            #** makes a integer
print(gamma)
print(type(gamma))      #use this if you forget what the class does

theta=3/3
print(theta)
print(type(theta))          #division make a float
theta=int(theta)            # this makes it an integer
print(theta)
print(type(theta))
theta=str(theta)            #this makes it a string
print(theta)
print(type(theta))

print("2"+"3")
print(2+3)
# is we try print(2+"3") it won't run because we can't add an integer and a string
#so we will either make both of them strings or make both of them integers
print(str(2)+"3")    #making both of them string
print(2+int("3"))    #making both of them integers
print(2+float(3))    #when you add float and integer, the answer will be float

