# -*- coding: utf-8 -*-
"""Python(day42).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6VXg4zXRq1PCQCdzwq5YLIgkvuefywy

8-1: Star
(a) Using ColabTurtle, use a for loop to draw a star with your turtle.
(b) Create a star() function with draws a star when called.
(c) Add a parameter to the star() function which controls the size of the star.
"""

from ColabTurtle.Turtle import *

initializeTurtle()

for i in range(5):
    forward(100)
    right(144)

done()

