# -*- coding: utf-8 -*-
"""Python(Day46).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFouN6XIcVkkj4Br6A_fkiOqV3N_Asl7
"""

class Car:
  """A simple attempt to make a car"""

  def __init__ (self,make,model,color):
    """Initialize car attributes:"""
    self.make = make
    self.model = model
    self.color = color
    #Fuel capacity and level in gallons.
    self.fuel_capacity = 100
    self.fuel_level = 150
car1= Car("GM","Corvette","Silver")
print(f"The fuel capacity is {car1.fuel_capacity}.")
print(f"The fuel level is {car1.fuel_level}.")