# -*- coding: utf-8 -*-
"""Python(day14).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq5zOsHDBT9dLyyQMzIhWQz-HaWbS89t
"""

#printing all items in a list
users=['val','bob','mia','ron','ned']
for user in users:
#for ____ in ____:
  print(f"{user} please come to my party.")
print([users])

#printing all items in a list
users=['val','bob','mia','ron','ned']
for user in users:
  print(f"{user} please come to my party.")
  print([users])
#anythig that is in the indentation is in the for loop.

"""Printing list with the text in a loop"""

animals= ['mouse','monkey','dog','cat']
for animal in animals:
  print (f"My favourite animal is a {animal}")
print(animals)
print(len(animals)) # count the total number of itmes in the list

animals= ['mouse','monkey','dog','cat']
for animal in animals:
  print("I have "+ str(len(animals)) +" animals at home.")

#printing the numbers 0 to 9
for x in range(10):
  print(x)

#printing it all in one line
for number in range(1,9):
 print(number, end=" , ")

#printing the number 5
for number in range(1,6):
  print(number)

numbers=list(range(1,11))
print(numbers)
type(numbers)
len(numbers)
#note: the type is not printed here because the last action is the only thing python will keep in memory

squares = []
for x in range(1,11):
  y= x**2
  squares.append(y)
print(squares)

for x in range(1,11):
  squares = [] #this is in the for loop so when we get the value, everytime, it becomes empty when it goes back to top to begin the loop again
  y= x**2
  squares.append(y)
  print(squares) #this print is inside the loop
print(squares)  #this print is outside the loop

"""Comprehending the above code"""

squares = [x**2 for x in range(1,11)]
print(squares)